name: Continous Integration

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npx eslint src/**/*.{ts,html}
      - run: npx prettier --check  src/**/*.{ts,html,css}
